### ISSUE TITLE
Identar correctamente el código

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-garcia-villanueva-godino#2]
Identar correctamente el código (en Webstorm con Ctrol+A se selecciona todo el código y con Ctrl+Alt+L ó menú Code > Reformat Code)

Se deben indentar todos los archivos marcados en celeste:
![imagen](https://github.com/UCC-LabCompu2/proyecto2024-garcia-villanueva-godino/assets/8345007/531b4669-4236-449d-8499-6965db55c1f3)

**Comment by edme88** [comment]
Acorde al webStorm, debe verificarse la identación de todos los archivos marcados en celeste:
![imagen](https://github.com/UCC-LabCompu2/proyecto2024-garcia-villanueva-godino/assets/8345007/d6030d86-9e29-4cbb-99e9-a1a409de5ad4)

**Comment by 2320413** [comment]
En el webstorm figuraban errores de ortografía, advertencias y advertencias menores. La página funciona con normalidad.
